spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auth_server
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate
    show-sql: false
  data:
    rest:
      default-media-type: application/json

server:
  port: 9090

logging:
  file:
    name: logger.log
    max-size: 10MB
    clean-history-on-start: false
  level:
    root: info
    com:
      tracker: info

app:
  isDevelopmentMode: true