spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auth_server
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate
    show-sql: false
  data:
    rest:
      default-media-type: application/json


security:
  oauth2:
    resource:
      jwt:
        key-uri: http://localhost:9090/oauth/token_key
    client:
      client_id: d615b1db-3fbb-4323-aa17-59668c3d3fd2
      client_secret: secret

server:
  port: 9090

logging:
  file:
    name: logger.log
    max-size: 10MB
    clean-history-on-start: false
  level:
    root: info
    com:
      tracker: info

app:
  isDevelopmentMode: true